/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AuctionInterface extends Interface {
    getFunction(nameOrSignature: "auctionCount" | "auctions" | "createAuction" | "endAuction" | "getAuction" | "pendingReturns" | "placeBid" | "withdrawBid"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuctionCreated" | "AuctionEnded" | "BidPlaced" | "BidWithdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'auctionCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'auctions', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createAuction', values: [string, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'endAuction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAuction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pendingReturns', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'placeBid', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawBid', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'auctionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'auctions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingReturns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawBid', data: BytesLike): Result;
  }

  
    export namespace AuctionCreatedEvent {
      export type InputTuple = [auctionId: BigNumberish, itemName: string, seller: AddressLike, deadline: BigNumberish];
      export type OutputTuple = [auctionId: bigint, itemName: string, seller: string, deadline: bigint];
      export interface OutputObject {auctionId: bigint, itemName: string, seller: string, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AuctionEndedEvent {
      export type InputTuple = [auctionId: BigNumberish, winner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [auctionId: bigint, winner: string, amount: bigint];
      export interface OutputObject {auctionId: bigint, winner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BidPlacedEvent {
      export type InputTuple = [auctionId: BigNumberish, bidder: AddressLike, amount: BigNumberish];
      export type OutputTuple = [auctionId: bigint, bidder: string, amount: bigint];
      export interface OutputObject {auctionId: bigint, bidder: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BidWithdrawnEvent {
      export type InputTuple = [auctionId: BigNumberish, bidder: AddressLike, amount: BigNumberish];
      export type OutputTuple = [auctionId: bigint, bidder: string, amount: bigint];
      export interface OutputObject {auctionId: bigint, bidder: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Auction extends BaseContract {
    
    connect(runner?: ContractRunner | null): Auction;
    waitForDeployment(): Promise<this>;

    interface: AuctionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    auctionCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    auctions: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, string, bigint, boolean] & {itemName: string, ipfsCID: string, seller: string, highestBid: bigint, highestBidder: string, deadline: bigint, ended: boolean }],
      'view'
    >
    

    
    createAuction: TypedContractMethod<
      [itemName: string, ipfsCID: string, startingPrice: BigNumberish, durationSeconds: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    endAuction: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAuction: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [[string, string, string, bigint, string, bigint, boolean]],
      'view'
    >
    

    
    pendingReturns: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    placeBid: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    withdrawBid: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'auctionCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'auctions'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, string, bigint, boolean] & {itemName: string, ipfsCID: string, seller: string, highestBid: bigint, highestBidder: string, deadline: bigint, ended: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'createAuction'): TypedContractMethod<
      [itemName: string, ipfsCID: string, startingPrice: BigNumberish, durationSeconds: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'endAuction'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAuction'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [[string, string, string, bigint, string, bigint, boolean]],
      'view'
    >;
getFunction(nameOrSignature: 'pendingReturns'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'placeBid'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'withdrawBid'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AuctionCreated'): TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
getEvent(key: 'AuctionEnded'): TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
getEvent(key: 'BidPlaced'): TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
getEvent(key: 'BidWithdrawn'): TypedContractEvent<BidWithdrawnEvent.InputTuple, BidWithdrawnEvent.OutputTuple, BidWithdrawnEvent.OutputObject>;

    filters: {
      
      'AuctionCreated(uint256,string,address,uint256)': TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
      AuctionCreated: TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
    

      'AuctionEnded(uint256,address,uint256)': TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
      AuctionEnded: TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
    

      'BidPlaced(uint256,address,uint256)': TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
      BidPlaced: TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
    

      'BidWithdrawn(uint256,address,uint256)': TypedContractEvent<BidWithdrawnEvent.InputTuple, BidWithdrawnEvent.OutputTuple, BidWithdrawnEvent.OutputObject>;
      BidWithdrawn: TypedContractEvent<BidWithdrawnEvent.InputTuple, BidWithdrawnEvent.OutputTuple, BidWithdrawnEvent.OutputObject>;
    
    };
  }