/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IAuction, IAuctionInterface } from "../../ReentrancyAttacker.sol/IAuction.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "auctionId",
        "type": "uint256"
      }
    ],
    "name": "placeBid",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "auctionId",
        "type": "uint256"
      }
    ],
    "name": "withdrawBid",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IAuction__factory {
    static readonly abi = _abi;
    static createInterface(): IAuctionInterface {
      return new Interface(_abi) as IAuctionInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IAuction {
      return new Contract(address, _abi, runner) as unknown as IAuction;
    }
  }
  