/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAuction } from './IAuction.js';
export type { ReentrancyAttacker } from './ReentrancyAttacker.js';